sudo: required
language: node_js
node_js:
  - 'stable'
cache:
directories:
  - node_modules
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - psql -c 'create user emeka with superuser createdb createrole;' -U postgres
  - psql -c 'create database travesty;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE travesty TO emeka;' -U postgres
  
  
script:
  - npm test
after_success:
  - npm run coverage